### ISSUE TITLE
Mem argument is not documented in readme

### ISSUE THREAD

**Issue by songololo** [chaulio/TiledVS#1]
@chaulio Interesting project / paper.

I was experimenting with using the viewshed analysis and noticed that the MEM command line argument is missing from the README.md command line parameters example.

i.e. 
`./TiledVS NROWS NCOLS OBSERVER[0] OBSERVER[1] OBSERVER_HEIGHT RADIUS INPUT_FILE.hgt [BLOCKSIZE_ROWS, BLOCKSIZE_COLS] > OUTPUT_FILE.vs`
should be
`./TiledVS NROWS NCOLS OBSERVER[0] OBSERVER[1] OBSERVER_HEIGHT RADIUS INPUT_FILE.hgt MEM(MB) [BLOCKSIZE_ROWS, BLOCKSIZE_COLS] > OUTPUT_FILE.vs`

Thanks.

**Comment by chaulio** [comment]
I've updated the Readme file. Thank you for pointing this!
